#全局端口定义server:
spring:
  aop:
    proxy-target-class: true
server:
  tomcat:
    uri-encoding: utf-8

#aliyun:
#  access-key-id: LTAI5tRuRbntuMYWh9WJ71YS
#  secret: 5izUvriMkI5sUDqwAW46vhVqyqGZQb
#  scenes: porn,terrorism,ad,qrcode,live,logo

